# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  formcore-js = nodeEnv.buildNodePackage {
    name = "formcore-js";
    packageName = "formcore-js";
    version = "0.1.89";
    src = fetchurl {
      url = "https://registry.npmjs.org/formcore-js/-/formcore-js-0.1.89.tgz";
      sha512 = "uZJoJxAoiVYJ0GQzyUIxwHZqYcv7tl75ZHCuZvjYPdBZhSkGBn0YpbdBu/K0vzrnWQH7XXK3ZuEnbkom1S1gRg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The FormCore minimal proof language";
      homepage = "https://github.com/moonad/formcorejs#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}